server:
  port: 8082
  servlet:
    context-path: /

spring:
  application:
    name: authentication-backend-service
  main:
    allow-bean-definition-overriding: true
  jpa:
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${SSO_CLIENT_ID}
            client-secret: ${SSO_CLIENT_SECRET}
            scope: openid
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: ${SSO_SERVER_URL}/auth/realms/${SSO_REALM_NAME}
            user-name-attribute: preferred_username
            token-uri: ${SSO_SERVER_URL}/realms/${SSO_REALM_NAME}/protocol/openid-connect/token
      resource-server:
        jwt:
          issuer-uri: ${SSO_SERVER_URL}/realms/${SSO_REALM_NAME}
###swagger
application:
  description: Authentication Backend Rest Api
  version: 1.0
build.date: 2023-10-04

###Timeout api
rest:
  template:
    read: 30000
    connect: 30000
