server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: spring3-template
  main:
    allow-bean-definition-overriding: true
  jpa:
    open-in-view: false
  kafka:
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers:
        - localhost:9092
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      bootstrap-servers:
        - localhost:9092
    listener:
      missing-topics-fatal: false
  data:
    mongodb:
      ngtu-template:
        uri: mongodb://mongo:mongo123@localhost:27017/ngtu_template?retryWrites=true&w=majority&directConnection=true&authMechanism=SCRAM-SHA-1&authSource=admin
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${SSO_CLIENT_ID}
            client-secret: ${SSO_CLIENT_SECRET}
            scope: openid
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/auth/realms/${SSO_REALM_NAME}
            user-name-attribute: preferred_username
            token-uri: http://localhost:8080/realms/${SSO_REALM_NAME}/protocol/openid-connect/token
        resource-server:
          jwt:
            issue-uri: http://localhost:8080/auth/realms/${SSO_REALM_NAME}
###swagger
application:
  description: ngtu Template
  version: 1.0
build.date: 2023-04-24

###Timeout api
rest:
  template:
    read: 300000
    connect: 300000

#  security:
#    oauth2:
#      client:
#        registration:
#          keycloak:
#            client-id: clientId
#            client-secret: uuid
#            scope: openid
#            authorization-grant-type: authorization_code
#        provider:
#          keycloak:
#            issuer-uri: https://kecloak.com
#            user-name-attribute: preferred_username
#      resourceserver:
#        jwt:
#          issuer-uri: https://kecloak.com

#keycloak:
#  enabled: false